all:	
	pdflatex 263_project_proposal.tex	
	bibtex 263_project_proposal.aux
	pdflatex 263_project_proposal.tex	
	pdflatex 263_project_proposal.tex	
	open 263_project_proposal.pdf

clean:
	rm *pdf *bbl *aux *blg *log
